version: '2'

services:
  mongo:
    image: mongo:3.6

  mgo-statsd:
    build: .
    image: scullxbones/mgo-statsd:latest
    command: >
      --mongo_address mongo
      -statsd_host statsd
      -interval 1s
      -statsd_env test
      -statsd_cluster test_mongo

  statsd:
    image: pataquets/statsd-debug
